blog/urls.py
from django.urls import path, include
from . import views

app_name = 'shadownetz_blog'

urlpatterns = [
    path('', views.index, name="index"),
    path('developershub/', include('developershub.urls')),
    path('social-life/', include('sociallife.urls')),
    path('food/', include('food.urls')),
    path('sports/', include('sports.urls')),
    path('movies/', include('movies.urls')),
    path('trending/', include('trending.urls')),
]

home/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'shadownetz'

urlpatterns = [
    path('', views.index, name="index"),
    # ProPush JS Verification
    path('sw-07c23.js', views.propush_js, name="propush-js"),

    path('contact', views.ContactView.as_view(), name="contact"),
    path('newsletter/signup', views.newsletter, name='newslettersignup'),
    path('status/email-origin', views.does_email_exist, name="emailOriginStatus")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

moderator/urls.py
from django.urls import path
from . import views
from .custom_views import (category_developershub_views, category_socialife_views,
                           category_food_views, category_sport_views,
                           category_movies_views, category_trending_views)

app_name = "shadownetz_moderator"

urlpatterns = [
    path('', views.index, name="index"),
    path('auth', views.auth, name="authentication"),
    path('auth/login', views.auth_login, name="authenticateLogin"),
    path('auth/logout', views.logout_user, name="logoutUser"),

    # Developers Hub Category
    path('categories/developershub', category_developershub_views.view_developers_hub_category, name="category_developershub"),
    path('categories/developershub/new', category_developershub_views.new_developers_hub_content, name="category_developershub_add"),
    path('categories/developershub/new/process', category_developershub_views.process_new_developers_hub_content,
         name="process_category_developershub_add"),
    path('categories/developershub/new/template/', category_developershub_views.new_developers_hub_content_from_template,
         name="category_developershub_add_template"),
    path('categories/developershub/new/template/process', category_developershub_views.process_new_developers_hub_content_from_template,
         name="process_category_developershub_add_template"),

    # Social Life Category
    path('categories/social-life', category_socialife_views.view_social_life_category,
         name="category_sociallife"),
    path('categories/social-life/new', category_socialife_views.new_social_life_content, name="category_sociallife_add"),
    path('categories/social-life/new/process', category_socialife_views.process_social_life_content,
         name="process_category_sociallife_add"),
    path('categories/social-life/new/template', category_socialife_views.new_social_life_content_from_template,
         name="category_sociallife_add_template"),
    path('categories/social-life/new/template/process', category_socialife_views.process_social_life_content_from_template,
         name="process_category_sociallife_add_template"),

    # Food Category
    path('categories/food', category_food_views.view_food_category, name="category_food"),
    path('categories/food/new', category_food_views.new_food_content, name="category_food_add"),
    path('categories/food/new/process', category_food_views.process_food_content,
         name="process_category_food_add"),
    path('categories/food/new/template', category_food_views.new_food_content_from_template, name="category_food_add_template"),
    path('categories/food/new/template/process', category_food_views.process_food_content_from_template,
         name="process_category_food_add_template"),

    # Sport Category
    path('categories/sport', category_sport_views.view_sport_category, name="category_sport"),
    path('categories/sport/new', category_sport_views.new_sport_content, name="category_sport_add"),
    path('categories/sport/new/process', category_sport_views.process_sport_content,
         name="process_category_sport_add"),
    path('categories/sport/new/template', category_sport_views.new_sport_content_from_template, name="category_sport_add_template"),
    path('categories/sport/new/template/process', category_sport_views.process_sport_content_from_template,
         name="process_category_sport_add_template"),

    # Movies Category
    path('categories/movies', category_movies_views.view_movies_category, name="category_movies"),
    path('categories/movies/new', category_movies_views.new_movies_content, name="category_movies_add"),
    path('categories/movies/new/process', category_movies_views.process_new_movies_content,
         name="process_category_movies_add"),
    path('categories/movies/new/template', category_movies_views.new_developers_hub_content_from_template, name="category_movies_add_template"),
    path('categories/movies/new/template/process', category_movies_views.process_new_developers_hub_content_from_template,
         name="process_category_movies_add_template"),

    # Trending Category
    path('categories/trending', category_trending_views.view_trending_category, name="category_trending"),
    path('categories/trending/new', category_trending_views.new_trending_content, name="category_trending_add"),
    path('categories/trending/new/process', category_trending_views.process_trending_content,
         name="process_category_trending_add"),
    path('categories/trending/new/template', category_trending_views.new_developers_hub_content_from_template, name="category_trending_add_template"),
    path('categories/trending/new/template/process', category_trending_views.process_new_developers_hub_content_from_template,
         name="process_category_trending_add_template"),


]

shadownetz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('moderator/', include('moderator.urls')),
]

trending/urls.py
from django.urls import path
from . import views

app_name = "shadownetz_trendingblog"

urlpatterns = [
    path('', views.index, name="index"),
    path('blog', views.display_blog, name="display_blog"),
    path('blog/post/comment', views.post_comment, name="post_comment"),
    path('blog/get/new-comment', views.fetch_latest_comment, name="fetch_new_comments")
]

trending/models.py
from django.db import models
from django.conf import settings


class TrendingBlog(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=100, blank=False)
    content = models.TextField(blank=False)
    tags = models.CharField(max_length=500, blank=True, null=True)
    views = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)
    url = models.URLField(blank=True)
    author = models.CharField(max_length=50, blank=True)
    display_image = models.URLField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + '_' + str(self.id) + '_blog'


class TrendingBlogComment(models.Model):
    user = models.EmailField(blank=False)
    blog = models.ForeignKey(settings.TRENDING_MODEL, on_delete=models.CASCADE)
    message = models.TextField(blank=False)
    date_created = models.DateTimeField(auto_now_add=True)

moderator/forms.py
from django import forms
from home.models import User


class LoginForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control text-center',
        'placeholder': "Email Address"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control text-center',
        'placeholder': 'Password'
    }))

moderator/scripts/forms/categories/food/forms.py
from django import forms


class NewContentForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Blog Title'
    }))
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control wysiwyg-editor', 'placeholder': 'Blog Content'
    }))
    tags = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': "Blog tags (separate with commas)"
    }), required=False)
    display_image = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': "Blog Display Image (URL)"
    }), required=False)

moderator/scripts/forms/categories/movies/forms.py
from django import forms


class NewContentForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Blog Title'
    }))
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control wysiwyg-editor', 'placeholder': 'Blog Content'
    }))
    tags = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': "Blog tags (separate with commas)"
    }), required=False)
    display_image = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': "Blog Display Image (URL)"
    }), required=False)

moderator/scripts/forms/categories/sociallife/forms.py
from django import forms


class NewContentForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Blog Title'
    }))
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control wysiwyg-editor', 'placeholder': 'Blog Content'
    }))
    tags = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': "Blog tags (separate with commas)"
    }), required=False)
    display_image = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': "Blog Display Image (URL)"
    }), required=False)

moderator/scripts/forms/categories/sports/forms.py
from django import forms


class NewContentForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Blog Title'
    }))
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control wysiwyg-editor', 'placeholder': 'Blog Content'
    }))
    tags = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': "Blog tags (separate with commas)"
    }), required=False)
    display_image = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': "Blog Display Image (URL)"
    }), required=False)

moderator/scripts/forms/categories/trending/forms.py
from django import forms


class NewContentForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Blog Title'
    }))
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control wysiwyg-editor', 'placeholder': 'Blog Content'
    }))
    tags = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': "Blog tags (separate with commas)"
    }), required=False)
    display_image = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': "Blog Display Image (URL)"
    }), required=False)

moderator/views.py
from django.shortcuts import render, reverse, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.admin.views.decorators import user_passes_test
from django.conf import settings
from .forms import *
from .scripts.forms.categories.developershub import forms as developershubforms


@user_passes_test(lambda x: True if x.is_staff and x.is_superuser else False,
                  login_url=settings.LOGIN_URL)
def index(request):
    return render(request, 'moderator/index.html', {})


def auth(request):
    login_form = LoginForm()
    context = {
        'loginForm': login_form
    }

    # failed login attempt
    try:
        context['loginErrorMessage'] = request.session['loginErrorMessage']
        del request.session['loginErrorMessage']
    except KeyError:
        pass

    return render(request, 'moderator/login.html', context)


def auth_login(request):
    auth_redirect = reverse('shadownetz_moderator:authentication')
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        nextURL = request.POST['next']
        if login_form.is_valid():
            email = login_form.cleaned_data['email']
            password = login_form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user=user)
                if len(nextURL) > 0:
                    return redirect(nextURL)
                return redirect(reverse('shadownetz_moderator:index'))
            else:
                request.session['loginErrorMessage'] = "Invalid Login Credentials"
        if len(nextURL) > 0:
            auth_redirect += "?next={}".format(nextURL)
    return redirect(auth_redirect)


def logout_user(request):
    logout(request)
    return redirect(reverse('shadownetz_moderator:authentication'))

trending/views.py
from django.shortcuts import render
from .app_functions import TrendingBlogClass
from django.http import JsonResponse

trending_blog_init = TrendingBlogClass()


def index(request):
    context = {
        "ready": True
    }
    page = request.GET.get('page')
    query = request.GET.get('q')
    if query:
        context['blogs'] = trending_blog_init.filter_blog_content_by_search(query, page, 5)
    else:
        context['blogs'] = trending_blog_init.get_blog_content(page, 5)
    return render(request, 'trending/index.html', context)


def display_blog(request):
    post_id = request.GET.get('post-id')
    comments = trending_blog_init.get_comments(post_id)
    context = {
        'blog': trending_blog_init.get_single_blog_content(post_id),
        'previous_blog': trending_blog_init.get_previous_single_blog_content(post_id),
        'next_blog': trending_blog_init.get_next_single_blog_content(post_id),
        'comments': comments[0],
        'number_of_comments': comments[1]
    }
    return render(request, 'trending/single-blog.html', context)


def post_comment(request):
    data = {'post_status': False}
    if request.method == 'POST':
        blog_id = request.POST['id']
        user_email = request.POST['email']
        message = request.POST['message']
        if user_email and message:
            post_status = trending_blog_init.post_comment(blog_id, user_email, message)
            if post_status:
                data['post_status'] = True
    return JsonResponse(data=data)


def fetch_latest_comment(request):
    if request.method == 'GET':
        data = {"new_comments": [], "new_no_of_comment": 0}
        index_of_last_comment = request.GET.get('last_comment_index')
        blog_id = request.GET.get('blog_id')

        try:
            index_of_last_comment = int(index_of_last_comment)
        except TypeError:
            index_of_last_comment = 0

        new_comment_objects = trending_blog_init.get_comment_greater_than_id(blog_id, index_of_last_comment)
        if new_comment_objects:
            for obj in new_comment_objects:
                tmp_obj = {'id': obj.id, 'user': obj.user, 'date_created': obj.date_created, 'message': obj.message}
                data["new_comments"].append(tmp_obj)
                data["new_no_of_comment"] = trending_blog_init.get_total_no_of_comment(blog_id)
        # data["new_comments"] = new_comment_objects[0] if new_comment_objects[0] else []
        return JsonResponse(data=data)

moderator/templates/moderator/categories/trending/dashboard.html
{% extends 'moderator/base.html' %}
{% load static %}
{% block title %}| Trending{% endblock %}
{% block content %}
    <section class="content">
        <header class="content__title">
            <h1>Dashboard
                <small>
                    Manage Trending Blog Content!
                </small>
            </h1>

            {#            <div class="actions">#}
            {#                <a href="#" class="actions__item zwicon-cog"></a>#}
            {#                <a href="#" class="actions__item zwicon-refresh-double"></a>#}
            {##}
            {#                <div class="dropdown actions__item">#}
            {#                    <i data-toggle="dropdown" class="zwicon-more-h"></i>#}
            {#                    <div class="dropdown-menu dropdown-menu-right">#}
            {#                        <a href="#" class="dropdown-item">Refresh</a>#}
            {#                        <a href="#" class="dropdown-item">Manage Widgets</a>#}
            {#                        <a href="#" class="dropdown-item">Settings</a>#}
            {#                    </div>#}
            {#                </div>#}
            {#            </div>#}
        </header>

        <div class="row quick-stats">
            <div class="col-sm-6 col-md-3">
                <a href="{% url 'shadownetz_moderator:category_trending_add' %}">
                    <div class="quick-stats__item">
                        <div class="quick-stats__info">
                            <h2><i class="zwicon-add-item" style="font-size:32px"></i></h2>
                            <small>Add</small>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-sm-6 col-md-3">
                <a href="{% url 'shadownetz_moderator:category_trending_add_template'%}?page=1">
                    <div class="quick-stats__item">
                        <div class="quick-stats__info">
                            <h2><i class="zwicon-add-item" style="font-size:32px"></i></h2>
                            <small>Add from template</small>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-sm-6 col-md-3">
                <div class="quick-stats__item">
                    <div class="quick-stats__info">
                        <h2>$58,778</h2>
                        <small>Total Sales Orders</small>
                    </div>

                    <div class="quick-stats__chart peity-bar">9,4,6,5,6,4,5,7,9,3,6</div>
                </div>
            </div>

            <div class="col-sm-6 col-md-3">
                <div class="quick-stats__item">
                    <div class="quick-stats__info">
                        <h2>214</h2>
                        <small>Total Support Tickets</small>
                    </div>

                    <div class="quick-stats__chart peity-bar">5,6,3,9,7,5,4,6,5,6,4</div>
                </div>
            </div>
        </div>


        <footer class="footer d-none d-sm-block">
            <p>© shadownetZ. All rights reserved.</p>

            <ul class="footer__nav">
                <a href="{% url 'shadownetz:index' %}" target="_blank">Homepage</a>
                <a href="{% url 'shadownetz_blog:index' %}" target="_blank">Blogs</a>
                <a href="{% url 'shadownetz:contact' %}" target="_blank">Contacts</a>
            </ul>
        </footer>
    </section>
{% endblock %}

moderator/templates/moderator/categories/trending/new_content_template.html
{% extends 'moderator/base.html' %}
{% load static %}
{% block title %}| Trending{% endblock %}
{% block link %}
    <link rel="stylesheet" href="{% static 'moderator/resources/vendors/trumbowyg/ui/trumbowyg.min.css' %}">
    <link rel="stylesheet" href="{% static 'moderator/resources/vendors/sweetalert2/sweetalert2.min.css' %}">
{% endblock %}
{% block content %}
    <section class="content">
        <header class="content__title">
            <h1>Add New Content
                <small>
                    Add new content to Trending Blog
                </small>
            </h1>

            {#            <div class="actions">#}
            {#                <a href="#" class="actions__item zwicon-cog"></a>#}
            {#                <a href="#" class="actions__item zwicon-refresh-double"></a>#}
            {##}
            {#                <div class="dropdown actions__item">#}
            {#                    <i data-toggle="dropdown" class="zwicon-more-h"></i>#}
            {#                    <div class="dropdown-menu dropdown-menu-right">#}
            {#                        <a href="#" class="dropdown-item">Refresh</a>#}
            {#                        <a href="#" class="dropdown-item">Manage Widgets</a>#}
            {#                        <a href="#" class="dropdown-item">Settings</a>#}
            {#                    </div>#}
            {#                </div>#}
            {#            </div>#}
        </header>

        <div class="row quick-stats">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Blog Templates</h4>
                        <h6></h6>

                        <div class="card-deck">

                            <div class="row">
                                {% if blogs %}
                                    {% for blog in blogs %}
                                        <div class="col-lg-4" style="margin-bottom: 20px">
                                            <div class="card" style="margin: auto 0">
                                                <form role="form" method="post" enctype="multipart/form-data" action="{% url 'shadownetz_moderator:process_category_trending_add_template' %}">
                                                    {% csrf_token %}
                                                    <img class="card-img-top" src="{{ blog.get_image }}" style="height: 150px">

                                                    <div class="card-body">
                                                        <h4 class="card-title">Title</h4>
                                                        <h6 class="card-subtitle">{{ blog.get_title }}</h6>

                                                        <div class="actions">
                                                            <button href="#" type="submit" class="btn-outline-success actions__item zwicon-upload" style="background: rgba(0,0,0,.5)"></button>
                                                        </div>

                                                        <p class="card-text">
                                                            {{ blog.get_content }}
                                                        </p>
                                                        <input type="hidden" name="post_title" value="{{ blog.get_title }}">
                                                        <input type="hidden" name="post_content" value="{{ blog.get_content }}">
                                                        <input type="hidden" name="post_tags" value="{{ blog.get_tags }}">
                                                        <input type="hidden" name="post_image" value="{{ blog.get_image }}">
                                                        <input type="hidden" name="post_date" value="{{ blog.get_date }}">
                                                        <input type="hidden" name="post_user" value="{{ blog.get_user }}">
                                                        <input type="hidden" name="post_url" value="{{ blog.get_url }}">
                                                    </div>

                                                </form>

                                            </div>
                                        </div>
                                    {% endfor %}
                                    <div class="col-12 justify-content-center">
                                        <a class="btn btn-theme-dark" id="js-prev-page" href="#">Previous Page</a>
                                        <a class="btn btn-theme-dark" id="js-nxt-page" href="#">Next Page</a>
                                        <input type="hidden" id="js-page-num" value="{{ request.GET.page }}">
                                        <input type="hidden" id="js-page-link" value="{% url 'shadownetz_moderator:category_trending_add_template'%}?page=">
                                    </div>
                                {% else %}
                                    <div class="col-12 text-center">
                                        <h5>No Template Available for now <i class="zwicon-folder-minus"></i></h5>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <br>
                    </div>
                </div>
            </div>


        </div>


        <footer class="footer d-none d-sm-block">
            <p>© shadownetZ. All rights reserved.</p>

            <ul class="footer__nav">
                <a href="{% url 'shadownetz:index' %}" target="_blank">Homepage</a>
                <a href="{% url 'shadownetz_blog:index' %}" target="_blank">Blogs</a>
                <a href="{% url 'shadownetz:contact' %}" target="_blank">Contacts</a>
            </ul>
        </footer>
    </section>
{% endblock %}
{% block script %}
    <script src="{% static 'moderator/resources/vendors/trumbowyg/trumbowyg.min.js' %}"></script>
    <script src="{% static 'moderator/resources/vendors/sweetalert2/sweetalert2.all.min.js' %}"></script>
    <script src="{% static 'moderator/custom/js/utils.js' %}"></script>
    <script src="{% static 'moderator/custom/categories/developershub/main.js' %}"></script>
    {% if add_content_save_status is True %}
        <script>
            displayAlert("top-right", "success", "Uploaded","Content Uploaded", 3000, 1000)
        </script>
    {% elif add_content_save_status is False%}
        <script>
            displayAlert("center", "error", "Error", "Content Upload failed", 2000, 1000)
        </script>
    {% endif %}
{% endblock %}